import 'package:flutter/foundation.dart';
import '../models/consultation_model.dart';

class ConsultationService {
  ConsultationService._privateConstructor();
  static final ConsultationService _instance =
      ConsultationService._privateConstructor();
  static ConsultationService get instance => _instance;

  final ValueNotifier<List<ConsultationSession>> sessions = ValueNotifier([]);

  /// Books a new consultation session (mocked for prototype)
  Future<ConsultationSession> bookSession(
    String userId,
    String therapistId,
    DateTime scheduledTime,
  ) async {
    // In reality, this would hit the backend POST /consultations/book
    // and retrieve the Agora RTC Channel Name and Token securely
    final newSession = ConsultationSession(
      id: 'session_${DateTime.now().millisecondsSinceEpoch}',
      userId: userId,
      therapistId: therapistId,
      scheduledTime: scheduledTime,
      rtcChannelName: 'safea_channel_$userId',
      securityToken: 'mock_token', // Real token generated by Agora backend
    );

    sessions.value = [...sessions.value, newSession];
    return newSession;
  }

  void dispose() {
    sessions.dispose();
  }
}
